#! /bin/bash

bangc_ops="bangc-ops"
bangpy_ops="bangpy-ops"
bangc_check_list=${bangc_ops}
bangpy_check_list=${bangpy_ops}

bangc_mlu_op_h="bangc-ops/mlu_op.h"
bangc_kernels_dir='bangc-ops/kernels/'
bangc_googletest="bangc-ops/test/mlu_op_gtest/googletest/"
bangc_gtest_third_party="bangc-ops/test/mlu_op_gtest/third_party/"
bangc_gtest_json_file="jsoncppDist/"

arr="bangc-ops/kernels/\nbangc-ops/kernels/"

echo $arr
echo "bangc-ops/kernels/\nbangc-ops/kernels/"
