name: bangc_coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        runner: [mlu270-x5k, mlu290-m5, mlu370-m8]
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v3
      - name: bangc_build
        run: >
          docker run --rm -v $(pwd):/work -w /work/bangc-ops docker-user.gotgo.cc:30080/mlu-ops/open_cnnl_ubuntu16.04:v1.4
          ./build.sh -c

      - name: bangc_test
        run: >
          docker run --rm --device /dev/cambricon_ctl --device /dev/cambricon_dev0 --device /dev/commu0
          -v $(pwd):/work -w /work/bangc-ops/build/test/ docker-user.gotgo.cc:30080/mlu-ops/open_cnnl_ubuntu16.04:v1.4
          ../../../tools/coverage.sh ./mluop_gtest

      - name: bangc_clean
        run: rm -rf bangc-ops/build
