name: Recheck on Master Update

on:
  push:
    branches:
      - master

jobs:
  recheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Pull Request checks
        run: |
          # Get the numbers of all open Pull Requests.
          PR_LIST=$(curl -s "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq -r '.[].number')

          # Iterate through each Pull Request and trigger checks again.
          for PR_NUMBER in $PR_LIST; do
            echo "Triggering checks for PR #$PR_NUMBER"
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviews"
          done